import { TvItem } from "./types";

export const TV_ITEMS: TvItem[] = [
  {
    id: 1,
    color: "#FF4D4D",
    rotation: -2,
    scale: 1.05,
    title: "Digital Symphony",
    artist: "Nam June Paik",
    gifUrl: "assets/어떤댄스.gif",
  },
  {
    id: 2,
    color: "#4DFFFF",
    rotation: 3,
    scale: 0.95,
    title: "Electronic Canvas",
    artist: "Lee Nam Lee",
    gifUrl: "assets/김밥가게.gif",
  },
  {
    id: 3,
    color: "#FFD700",
    rotation: -1,
    scale: 1,
    title: "Virtual Waves",
    artist: "Kim Nam June",
    gifUrl: "assets/우주전쟁.gif",
  },
  {
    id: 4,
    color: "#FF69B4",
    rotation: 2,
    scale: 1.02,
    title: "Digital Dreams",
    artist: "Park Hyun-Ki",
    gifUrl: "assets/mbti.gif",
  },
  {
    id: 5,
    color: "#98FB98",
    rotation: -3,
    scale: 0.98,
    title: "Neon Nights",
    artist: "Shin Sung Hy",
    gifUrl: "assets/theknight.gif",
  },
  {
    id: 6,
    color: "#DDA0DD",
    rotation: 1,
    scale: 1.03,
    title: "Electric Echo",
    artist: "Moon Kyungwon",
    gifUrl: "assets/url-shortener.gif",
  },
  {
    id: 7,
    color: "#87CEEB",
    rotation: -2,
    scale: 0.97,
    title: "Pixel Poetry",
    artist: "Jeon Joonho",
    gifUrl: "assets/비건앱예제.gif",
  },
  {
    id: 8,
    color: "#FFA07A",
    rotation: 2,
    scale: 1.01,
    title: "Binary Beauty",
    artist: "Yang Haegue",
    gifUrl: "assets/몬스터팜.gif",
  },
];
